[build]
  command = """
  sed -i 's|baseUrl:.*|baseUrl: "/",|I' docusaurus.config.js
  wget -qO- https://raw.githubusercontent.com/pranabdas/espresso/refs/heads/main/scripts/build_docusaurus.sh | bash
  """

  publish = "build"

[build.environment]
  NODE_VERSION = "lts/*"
